zebra_reader:
  host: 10.165.17.146
  port: 5084

snipeit:
  base_url: "http://localhost:3000"
  api_token: "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiMjc5NTU3ZGU1ODdmZDk2ZTRiYjJhYjliYjM0MjFjZDU0Njg1MjU2MmQ2YTBjZGM4NjZlODU4NGQzYWU2ZjY2M2UzMzAyNGJiNmI1MmVlMzAiLCJpYXQiOjE3NjMyMjYxODkuNDUyNzUyLCJuYmYiOjE3NjMyMjYxODkuNDUyNzU1LCJleHAiOjIyMzY2MTE3ODkuNDI3MzgzLCJzdWIiOiIxIiwic2NvcGVzIjpbXX0.DkomgwhwCg1BLVoQ3WnW7afas4SrPab145AsBGgFuegwUr-9BiQ28TlTuJ7Wb0vQ3pgrk5Jf5ync81B0GKvAz_zPkf8HrOSaOe0JMIl9aLHrqb58w9_ksftqEEL7cSQQKEk2njr913Kmc_EVuCCKJD9329GuNDA8woLguEzFzZBURiVczQhcWbwwRTD6uUZ9c-mgqUDnR4Q4G7vChz4HujtM_Unlahp0zhCJHU7Kia0pJvxaNonaPwyPkXqN107rHKPUWQG2HQTFo7mYt6ZbQxWaAhXmXsBgcZ8kXzoH2gehdeGnvsNvhv0dtaEPsfnpvxfQUMPYFyMZM2S8ooJ2XihnJvf4ou6vspdIvT4U-ZvM4KW2zu4GEJ3iD5HTrDlYzpy3Qh839YoEEpIWqjJq4S1vn8Yyb0tqbGPsCVUntfyK694xZNXxmGGW9YFhFQFN-2pP_SAkmbTzn3MrOlROAzhI4Ox1ZRAFKH4g1Z1t_1tGIw80bSdGstJCHrbP4PRzq0IMW-Wz7Ot-wOCWHOvcTLmrw8taAL29qv02u3h3hsIfe0kXU_ddOWGp3vO12HetRsjXDbMXs9TdQcekBZuPnHx1pJhfL4QnAPaDloAa-3E3HMQyBUZaqnrhtJ7k6FMCz0QfRjpZ3qvsAe_5aqgIZdN-xV8t1Jux5b8VRGIKxgw"  # Replace with your actual API token

locations:
  dock_entry: 55  
  dock_exit: 3  
  warehouse:  114 

logging:
  level: "INFO"
  file: "logs/agent.log"
  unknown_tags_file: "logs/unknown_tags.log"

